; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Device 1 - COM7 
[env:device1_com7]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = COM7
monitor_port = COM7

; Device 2 - COM6
[env:device2_com6] 
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = COM6
monitor_port = COM6
